name: Enhanced Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # terraform-docs: Not needed for root directory (no .tf files)
  # Module documentation is handled by terraform-docs in each module directory

  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true
          output_format: sarif
          download_external_modules: true

      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - modules/auditledger-s3
          - modules/auditledger-azure-blob

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init
        working-directory: ${{ matrix.module }}

      - name: Run TFLint
        run: tflint --format compact
        working-directory: ${{ matrix.module }}
